Fix descriptions according to the upgraded draft
w3c/webrtc-stats pull request #689
Opened 2022-09-24 08:30 UTC by balazskreith

* Remove description reference to non-existing-field totalSamplesDecoded

2022-10-04 09:43 UTC, vr000m commented
hmmm... we should link to `totalSamplesDecoded` in the provisional spec. @dontcallmedom is there a way to do this, apart from hyperlinking directly? https://w3c.github.io/webrtc-provisional-stats/#dom-rtcinboundrtpstreamstats-totalsamplesdecoded

2022-10-04 13:20 UTC, henbos approved these changes

2022-10-04 13:23 UTC, henbos requested changes
We should make totalProcessingDelay video-only since it's only implemented for video, then it makes sense to not reference totalSamplesDecoded

2022-10-04 13:25 UTC, alvestrand commented
The issue #660 is about marking up the stats that are only implemented for one stat.

2022-10-18 13:20 UTC, closed without merging

2022-10-18 13:20 UTC, henbos commented
Let's follow up in #660